Use poppler-config.h instead of aconf.h.
Note that this also fixes an undefined reference to GooString::copy().
This appears to tbe due to the use of the GCC "interface" pragma that
prevents copies of inline member functions being emitted.